# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: BrettTest
    
    container: 
      image: brmclare/oesdk-windows2019-sgx:510
      options: -it --device="class/17eaf82e-e167-4763-b569-5b8273cef6e1"

    steps:
      - script: cd & mkdir temp && cd temp && git clone --recursive https://github.com/openenclave/openenclave.git && cd openenclave && cd && git checkout v0.9.x && mkdir build && cd build && mkdir x64-Debug && cd x64-Debug && vcvars64.bat && cmake -G Ninja -DLVI_MITIGATION=ControlFlow -DNUGET_PACKAGE_PATH=C:\Downloads\prereqs\nuget -DCMAKE_INSTALL_PREFIX=C:/openenclave ../.. && ninja && ctest