# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Image
    displayName: Build Image
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'brmclareDockerHub'
        repository: 'brmclare/oesdk-windows2019-sgx-dev'
        command: 'buildAndPush'
        Dockerfile: 'openenclave-sdk\windows-2019\Dockerfile'
        tags: |
          $(Build.BuildId)
  - job: Build2
    dependsOn: Image
    displayName: Build OE
    pool:
      name: BrettTest
    
    container: 
      image: brmclare/oesdk-windows2019-sgx:$(Build.BuildId)
      options: -it --device="class/17eaf82e-e167-4763-b569-5b8273cef6e1"

    steps:
      - script: mkdir temp && cd temp && git clone https://github.com/openenclave/openenclave.git && cd openenclave && git checkout v0.9.x && mkdir out && cd out && mkdir x64-Debug && cd x64-Debug && vcvars64.bat &&cmake -G Ninja -DLVI_MITIGATION=ControlFlow -DNUGET_PACKAGE_PATH=C:\Downloads\prereqs\nuget -DCMAKE_INSTALL_PREFIX=C:/openenclave ../.. && ninja && ctest