# Use server core instead of nano because installing powershell is hard..
FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY install.* C:\\

#RUN C:\install.cmd

#RUN del C:\install.*

#COPY build.* C:\
#COPY cleanup.* C:\

#RUN build.cmd
#RUN cleanup.cmd